# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/grafana/main/conf/provisioning/datasources/_example.yaml

apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true